"""empty message

Revision ID: 2d47afca4a2
Revises: 5674280f566
Create Date: 2017-02-11 16:57:23.306803

"""

# revision identifiers, used by Alembic.
revision = '2d47afca4a2'
down_revision = '5674280f566'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
