"""empty message

Revision ID: 4569d08921e
Revises: caa5929b94
Create Date: 2017-01-20 16:25:30.299363

"""

# revision identifiers, used by Alembic.
revision = '4569d08921e'
down_revision = 'caa5929b94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
