"""initial migration

Revision ID: 4f846b7bc57
Revises: 38c4e85512a9
Create Date: 2017-01-14 10:44:45.523231

"""

# revision identifiers, used by Alembic.
revision = '4f846b7bc57'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
