"""empty message

Revision ID: 51636ccaa63
Revises: 12665c162c8
Create Date: 2017-01-17 14:13:56.251527

"""

# revision identifiers, used by Alembic.
revision = '51636ccaa63'
down_revision = '12665c162c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
