"""empty message

Revision ID: caa5929b94
Revises: 3079cce1852
Create Date: 2017-01-19 10:46:08.782478

"""

# revision identifiers, used by Alembic.
revision = 'caa5929b94'
down_revision = '3079cce1852'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
